#!/usr/bin/env python3
"""Turn data/mta_stations.csv into docs/data/stations.js for the static web page.

This mirrors load_mta_stations() in app.R: stations are keyed on name plus
lat/lon rounded to 4 decimals, the daytime routes of every matching row are
unioned, and the coordinates are averaged. Running it produces a plain
<script>-loadable file so the page needs no fetch() and works over file://.

Usage:  python3 tools/build_stations_data.py
"""

import argparse
import collections
import csv
import json
import os
import statistics

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SRC = os.path.join(REPO, "data", "mta_stations.csv")
DEFAULT_OUT = os.path.join(REPO, "docs", "data", "stations.js")

# Display order for the route picker: MTA trunk-line grouping, which reads far
# better than the plain alphabetical sort. Routes found in the CSV but missing
# here are appended so new data never silently drops a route.
ROUTE_ORDER = [
    "1", "2", "3", "4", "5", "6", "7",
    "A", "C", "E", "B", "D", "F", "M",
    "G", "J", "Z", "L", "N", "Q", "R", "W", "S", "SIR",
]


def load_rows(path):
    with open(path, newline="", encoding="utf-8-sig") as fh:
        return list(csv.DictReader(fh))


def build(rows):
    groups = collections.OrderedDict()

    for row in rows:
        name = (row.get("Stop Name") or "").strip()
        raw_lat = (row.get("GTFS Latitude") or "").strip()
        raw_lon = (row.get("GTFS Longitude") or "").strip()
        if not name or not raw_lat or not raw_lon:
            continue
        try:
            lat, lon = float(raw_lat), float(raw_lon)
        except ValueError:
            continue

        key = (name, round(lat, 4), round(lon, 4))
        grp = groups.setdefault(
            key, {"name": name, "routes": set(), "lats": [], "lons": [], "borough": "", "ada": 0}
        )
        grp["routes"].update((row.get("Daytime Routes") or "").split())
        grp["lats"].append(lat)
        grp["lons"].append(lon)
        grp["borough"] = grp["borough"] or (row.get("Borough") or "").strip()
        try:
            # Within a complex the rows can disagree; keep the most accessible.
            grp["ada"] = max(grp["ada"], int((row.get("ADA") or "0").strip() or 0))
        except ValueError:
            pass

    stations = []
    for grp in groups.values():
        if not grp["routes"]:
            continue
        stations.append(
            {
                "n": grp["name"],
                # sorted() matches the ASCII ordering R's sort() produces here.
                "l": ",".join(sorted(grp["routes"])),
                "y": round(statistics.fmean(grp["lats"]), 6),
                "x": round(statistics.fmean(grp["lons"]), 6),
                "b": grp["borough"],
                "a": grp["ada"],
            }
        )

    seen = sorted({r for s in stations for r in s["l"].split(",")})
    routes = [r for r in ROUTE_ORDER if r in seen] + [r for r in seen if r not in ROUTE_ORDER]
    return stations, routes


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", default=DEFAULT_SRC, help="MTA stations CSV")
    ap.add_argument("--out", default=DEFAULT_OUT, help="generated JS file")
    args = ap.parse_args()

    stations, routes = build(load_rows(args.src))
    payload = {
        "source": os.path.relpath(args.src, REPO),
        "count": len(stations),
        "routes": routes,
        "stations": stations,
    }

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/build_stations_data.py — do not edit by hand.\n")
        fh.write("// Regenerate after changing %s.\n" % payload["source"])
        fh.write("var MTA_STATIONS = %s;\n" % body)
        fh.write("if (typeof module !== 'undefined' && module.exports) module.exports = MTA_STATIONS;\n")
        fh.write("if (typeof window !== 'undefined') window.MTA_STATIONS = MTA_STATIONS;\n")

    print("wrote %s — %d stations, %d routes (%s)"
          % (os.path.relpath(args.out, REPO), len(stations), len(routes), ", ".join(routes)))


if __name__ == "__main__":
    main()
